#!/usr/bin/env bash
set -euo pipefail

IMAGE_NAME="${IMAGE_NAME:-symlink-editor}"
CONTAINER_NAME="${CONTAINER_NAME:-symlink-editor}"
HOST_PORT="${HOST_PORT:-8080}"
FILMS_DIR="${FILMS_DIR:-$PWD/films}"
FILMS_ROOT="${FILMS_ROOT:-/mnt/3DFF}"
SYMLINK_EDITOR_HOST="${SYMLINK_EDITOR_HOST:-192.168.1.14}"
SYMLINK_EDITOR_PORT="${SYMLINK_EDITOR_PORT:-8080}"

mkdir -p "$FILMS_DIR"

docker build -t "$IMAGE_NAME" .

docker run --rm \
  --name "$CONTAINER_NAME" \
  -p "$HOST_PORT":8080 \
  -e FILMS_ROOT="$FILMS_ROOT" \
  -e SYMLINK_EDITOR_HOST="$SYMLINK_EDITOR_HOST" \
  -e SYMLINK_EDITOR_PORT="$SYMLINK_EDITOR_PORT" \
  -v "$FILMS_DIR":"$FILMS_ROOT" \
  "$IMAGE_NAME"
