FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    FILMS_ROOT=/mnt/3DFF \
    SYMLINK_EDITOR_HOST=192.168.1.14 \
    SYMLINK_EDITOR_PORT=8080

WORKDIR /app
COPY app.py /app/app.py

EXPOSE 8080

VOLUME ["/mnt/3DFF"]

CMD ["python", "/app/app.py"]
